#!/bin/sh

# Set these paths appropriately

BIN="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/bin"
CMD="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/cmd"
LIB="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

