#!/bin/sh

# Set these paths appropriately

BIN="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/bin"
CMD="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/cmd"
LIB="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
