#!/bin/sh

# Set these paths appropriately

BIN="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/bin"
CMD="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/cmd"
LIB="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

