#!/bin/sh

# Set these paths appropriately

BIN="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/bin"
CMD="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/cmd"
LIB="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
