#!/bin/sh

# Set these paths appropriately

BIN="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/bin"
CMD="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/cmd"
LIB="/c/Users/Irina/PycharmProjects/ADWISER/website/tt/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/finnish-abbreviations
PARFILE=${LIB}/finnish.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE

